services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
    volumes:
      - ./oracle-init:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/oracle@localhost/FREEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10

  springboot-app:
    build:
      context: .
    container_name: springboot
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: IEZ
      SPRING_DATASOURCE_PASSWORD: iez123
    ports:
      - "8601:8601"
